const EventTags = [
  { label: 'Live Music', tagId: 'live_music' },
  { label: 'Art Exhibit', tagId: 'art_exhibit' },
  { label: 'Film Screening', tagId: 'film_screening' },
  { label: 'Stand-Up Comedy', tagId: 'stand_up_comedy' },
  { label: 'Theatre Play', tagId: 'theatre_play' },
  { label: 'Music Festival', tagId: 'music_festival' },
  { label: 'Food Festival', tagId: 'food_festival' },
  { label: 'Cultural Parade', tagId: 'cultural_parade' },
  { label: 'Street Fair', tagId: 'street_fair' },
  { label: 'Business Conference', tagId: 'business_conference' },
  { label: 'Startup Pitch', tagId: 'startup_pitch' },
  { label: 'Product Launch', tagId: 'product_launch' },
  { label: 'Networking Event', tagId: 'networking_event' },
  { label: 'Workshop', tagId: 'workshop' },
  { label: 'Seminar', tagId: 'seminar' },
  { label: 'Coding Bootcamp', tagId: 'coding_bootcamp' },
  { label: 'Tech Talk', tagId: 'tech_talk' },
  { label: 'Hackathon', tagId: 'hackathon' },
  { label: 'Webinar', tagId: 'webinar' },
  { label: 'Online Workshop', tagId: 'online_workshop' },
  { label: 'Virtual Meetup', tagId: 'virtual_meetup' },
  { label: 'Online Concert', tagId: 'online_concert' },
  { label: 'Sports Match', tagId: 'sports_match' },
  { label: 'Esports Tournament', tagId: 'esports_tournament' },
  { label: 'Fitness Challenge', tagId: 'fitness_challenge' },
  { label: 'Yoga Retreat', tagId: 'yoga_retreat' },
  { label: 'Marathon', tagId: 'marathon' },
  { label: 'Health Seminar', tagId: 'health_seminar' },
  { label: 'Mental Wellness', tagId: 'mental_wellness' },
  { label: 'Fundraising Gala', tagId: 'fundraising_gala' },
  { label: 'Charity Auction', tagId: 'charity_auction' },
  { label: 'Volunteer Meetup', tagId: 'volunteer_meetup' },
  { label: 'Church Service', tagId: 'church_service' },
  { label: 'Religious Conference', tagId: 'religious_conference' },
  { label: 'Spiritual Retreat', tagId: 'spiritual_retreat' },
  { label: 'Wedding Expo', tagId: 'wedding_expo' },
  { label: 'Birthday Party', tagId: 'birthday_party' },
  { label: 'Anniversary Celebration', tagId: 'anniversary_celebration' },
  { label: 'Baby Shower', tagId: 'baby_shower' },
  { label: 'Carnival', tagId: 'carnival' },
  { label: 'Book Launch', tagId: 'book_launch' },
  { label: 'Poetry Night', tagId: 'poetry_night' },
  { label: 'Fashion Show', tagId: 'fashion_show' },
  { label: 'Dance Battle', tagId: 'dance_battle' },
  { label: 'Photography Exhibition', tagId: 'photo_exhibition' },
  { label: 'Themed Party', tagId: 'themed_party' },
  { label: 'Tech Expo', tagId: 'tech_expo' },
  { label: 'Career Fair', tagId: 'career_fair' },
  { label: 'Startup Demo Day', tagId: 'startup_demo_day' },
  { label: 'Science Fair', tagId: 'science_fair' },
  { label: 'Debate Competition', tagId: 'debate_competition' },
  { label: 'Art Workshop', tagId: 'art_workshop' }
];

export default EventTags