export const englishEventTags = [
  { id: "1", tag: "Conference", category: "Professional" },
  { id: "2", tag: "Workshop", category: "Professional" },
  { id: "3", tag: "Seminar", category: "Professional" },
  { id: "4", tag: "Webinar", category: "Online" },
  { id: "5", tag: "Networking", category: "Professional" },
  { id: "6", tag: "Fundraiser", category: "Community" },
  { id: "7", tag: "Festival", category: "Cultural" },
  { id: "8", tag: "Concert", category: "Cultural" },
  { id: "9", tag: "Exhibition", category: "Cultural" },
  { id: "10", tag: "Trade Show", category: "Professional" },
  { id: "11", tag: "Product Launch", category: "Professional" },
  { id: "12", tag: "Ceremony", category: "Community" },
  { id: "13", tag: "Panel Discussion", category: "Professional" },
  { id: "14", tag: "Hackathon", category: "Professional" },
  { id: "15", tag: "Meetup", category: "Community" },
  { id: "16", tag: "Retreat", category: "Community" },
  { id: "17", tag: "Competition", category: "Sports" },
  { id: "18", tag: "Award Show", category: "Cultural" },
  { id: "19", tag: "Community Gathering", category: "Community" },
  { id: "20", tag: "Charity Event", category: "Community" },
  { id: "21", tag: "Virtual Conference", category: "Online" },
  { id: "22", tag: "Online Workshop", category: "Online" },
  { id: "23", tag: "Live Stream", category: "Online" },
  { id: "24", tag: "Virtual Networking", category: "Online" },
  { id: "25", tag: "Hybrid Event", category: "Online" },
  { id: "26", tag: "Online Panel", category: "Online" },
  { id: "27", tag: "Virtual Expo", category: "Online" },
  { id: "28", tag: "Digital Summit", category: "Online" },
  { id: "29", tag: "Online Training", category: "Online" },
  { id: "30", tag: "Virtual Meetup", category: "Online" },
  { id: "31", tag: "Online Fundraiser", category: "Online" },
  { id: "32", tag: "Virtual Concert", category: "Online" },
  { id: "33", tag: "Remote Collaboration", category: "Online" },
  { id: "34", tag: "Online Community Event", category: "Online" },
  { id: "35", tag: "Match", category: "Sports" },
  { id: "36", tag: "Sports Match", category: "Sports" },
  { id: "37", tag: "Esports Match", category: "Online" },
  { id: "38", tag: "Matchmaking Event", category: "Community" },
];

export const frenchEventTags = [
  { id: "1", tag: "Conférence", category: "Professionnel" },
  { id: "2", tag: "Atelier", category: "Professionnel" },
  { id: "3", tag: "Séminaire", category: "Professionnel" },
  { id: "4", tag: "Webinaire", category: "En ligne" },
  { id: "5", tag: "Réseautage", category: "Professionnel" },
  { id: "6", tag: "Collecte de fonds", category: "Communauté" },
  { id: "7", tag: "Festival", category: "Culturel" },
  { id: "8", tag: "Concert", category: "Culturel" },
  { id: "9", tag: "Exposition", category: "Culturel" },
  { id: "10", tag: "Salon professionnel", category: "Professionnel" },
  { id: "11", tag: "Lancement de produit", category: "Professionnel" },
  { id: "12", tag: "Cérémonie", category: "Communauté" },
  { id: "13", tag: "Table ronde", category: "Professionnel" },
  { id: "14", tag: "Hackathon", category: "Professionnel" },
  { id: "15", tag: "Rencontre", category: "Communauté" },
  { id: "16", tag: "Retraite", category: "Communauté" },
  { id: "17", tag: "Compétition", category: "Sport" },
  { id: "18", tag: "Remise de prix", category: "Culturel" },
  { id: "19", tag: "Rassemblement communautaire", category: "Communauté" },
  { id: "20", tag: "Événement caritatif", category: "Communauté" },
  { id: "21", tag: "Conférence virtuelle", category: "En ligne" },
  { id: "22", tag: "Atelier en ligne", category: "En ligne" },
  { id: "23", tag: "Diffusion en direct", category: "En ligne" },
  { id: "24", tag: "Réseautage virtuel", category: "En ligne" },
  { id: "25", tag: "Événement hybride", category: "En ligne" },
  { id: "26", tag: "Table ronde en ligne", category: "En ligne" },
  { id: "27", tag: "Expo virtuelle", category: "En ligne" },
  { id: "28", tag: "Sommet numérique", category: "En ligne" },
  { id: "29", tag: "Formation en ligne", category: "En ligne" },
  { id: "30", tag: "Rencontre virtuelle", category: "En ligne" },
  { id: "31", tag: "Collecte de fonds en ligne", category: "En ligne" },
  { id: "32", tag: "Concert virtuel", category: "En ligne" },
  { id: "33", tag: "Collaboration à distance", category: "En ligne" },
  { id: "34", tag: "Événement communautaire en ligne", category: "En ligne" },
  { id: "35", tag: "Match", category: "Sport" },
  { id: "36", tag: "Match sportif", category: "Sport" },
  { id: "37", tag: "Match d'e-sport", category: "En ligne" },
  { id: "38", tag: "Événement de mise en relation", category: "Communauté" },
];
